import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeNavBar from '../components/home/HomeNavBar';
import HomeDrawer from '../components/home/HomeDrawer';
import { useState } from "react";
import { Carousel } from '../components/home/Carousel';

const pages = ['Home', 'Menù', 'Dove siamo', 'Contattaci'];

export default function Home() {
  const [openDrawer, setOpenDrawer] = useState(false);

  return (
    <div>
      <Head>
        <title>Pizzeria San Michele</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" /> // MUI: To ensure proper rendering and touch zooming for all devices
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeNavBar setOpenDrawer={setOpenDrawer} pages={pages}/>
        <HomeDrawer open={openDrawer} setOpen={setOpenDrawer} pages={pages}/>
        <Carousel />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
